title: Dr. Farhana Islam # Shown in header on pages with full_logo: true
short_logo: Dr. Farhana Islam # Shown in header on all pages by default unless full_logo: true is set
description: > # The description for your site
  Hi, Iâ€™m Farhana. I am a researcher, educator, and life-long learner. I have a PhD from the Department of Pharmacology and Toxicology at the University of Toronto. My doctoral research, in the field of Psychiatric Pharmacogenetics, investigated the genetic contribution to antidepressant and antipsychotic drug response, side effects, and pharmacokinetics in individuals with depression and schizophrenia.
url: "https://drfarhanaislam.github.io" # Site base URL

author:
  name: Farhana Islam
  github: drfarhanaislam # GitHub username, used for GitHub icon on the top right
  linkedin: https://www.linkedin.com/in/farhanai/  # Your LinkedIn profile url name, used for LinkedIn icon on the top right
  email: farhanaislam@hotmail.com # Used for email icon on the top right
  homepage: https://ritijjain.com # This links to your name in post meta
  twitter: FarhanaI7 # Twitter username, used for Twitter Card Analytics
  google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=wFqLDl0AAAAJ 

disqus_name: # Setting this will turn on Disqus comments
g_track_id: # Google Analytics tracking ID (e.g. UA-000000-2), setting this will turn on Google Analytics

markdown: kramdown

defaults: # Recommended defaults, you may set your own
  -
    scope:
      path: _posts
    values:
      comments: true
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false
  -
    scope:
      path: pages/tags
    values:
      layout: tag
      sitemap:
        priority: 0.4

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: [html, head, body]

rss: false # RSS feed icon on or off
dark_mode: true # Dark mode icon
project_card_style: modal # Choose from masonry, modal, and flat
